# This is a basic workflow to help you get started with Actions

name: NOAA STAC

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    workflow_dispatch:
    schedule:
      - cron: "50 15 * * * "

jobs:
  conda:
    name: Conda ${{ matrix.python-version }} - ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.9']

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        path: usgs-lidar
    - name: Install prerequisites
      shell: bash -l {0}
      run: |
          conda config --add channels conda-forge
          conda install -c conda-forge pdal pystac Shapely pyproj Fiona nodejs -y
          cd action; pip install requests boto3 awscli; pip install -e .
          npm install -g topojson-server
    - name: Create NOAA STAC
      shell: bash -l {0}
      working-directory: action/usgs_boundary
      run: |
        python noaa.py
        ls noaa_stac/

      # env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}