name: NOAA STAC

on:
    workflow_dispatch:
    schedule:
      - cron: "50 15 * * * "

jobs:
  conda:
    name: Conda ${{ matrix.python-version }} - ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.9']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install prerequisites
      shell: bash -l {0}
      run: |
        pip install 'pystac[validation]' pyproj shapely boto3
    - name: Create NOAA STAC
      shell: bash -l {0}
      working-directory: action/usgs_boundary
      run: |
        python noaa.py
        ls noaa_stac/
        aws s3 sync noaa_stac s3://usgs-lidar-stac/noaa/ --acl public-read --region us-west-2
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'
